name: Cross-compile Racediffer

on:
  workflow_dispatch:
  push:
    branches:
      - main
  

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: thatisuday/go-cross-build@v1
        with:
          platforms: linux/amd64, windows/amd64, darwin/amd64, darwin/arm64
          package: ''
          name: racediffer
          dest: dist
      - uses: softprops/action-gh-release@v1
        with:
          files: dist/*
          name: ${{ github.event.head_commit.name }}
          tag_name: ${{ github.event.head_commit.sha }}
          prerelease: false
