name: Cross-compile Racediffer

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.18

      - name: Cross-compile
        run: |
          GOOS=linux GOARCH=amd64 go build -o racediffer_linux_amd64 .
          GOOS=darwin GOARCH=amd64 go build -o racediffer_darwin_amd64 .
          GOOS=windows GOARCH=amd64 go build -o racediffer_windows_amd64.exe .

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            racediffer_linux_amd64
            racediffer_macos_amd64
            racediffer_windows_amd64.exe
          tag_name: ${{ github.sha }}
          release_name: racediffer
